apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\system32\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mynginx
  name: mynginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mynginx
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\WINDOWS\system32\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/app-network: "true"
        io.kompose.service: mynginx
    spec:
      containers:
      - image: yushengze/mynginx:latest
        imagePullPolicy: ""
        name: mynginx
        ports:
        - containerPort: 80
        resources: {}
        securityContext:
          privileged: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
