apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\system32\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: phpmyadmin
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: phpmyadmin
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\WINDOWS\system32\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/app-network: "true"
        io.kompose.service: phpmyadmin
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: MyDBRoot123
        - name: MYSQL_USERNAME
          value: root
        - name: PMA_ARBITRARY
          value: "1"
        - name: PMA_HOST
          value: mysql
        - name: PMA_PORT
          value: "3306"
        image: phpmyadmin/phpmyadmin
        imagePullPolicy: ""
        name: pma
        ports:
        - containerPort: 80
        resources: {}
        securityContext:
          privileged: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
